# Generated by Django 2.1.3 on 2018-11-16 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kencleng_core', '0002_transksi_prmilik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transksi',
            name='prmilik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
